version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${PORT_NGINX}:80
    volumes:
      - ${PROJECT_PATH}:/var/www/project:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d:cached
      - ./var/logs/nginx/:/var/log/nginx

  php:
    build:
      context: docker/php
      args:
        PHP_USER_ID: ${PHP_USER_ID}
    user: ${PHP_USER_ID}
    volumes:
      - ${PROJECT_PATH}:/var/www/project:cached
      - ./var/data/php/workspace:/var/www/workspace:cached
      - ${COMPOSER_CACHE_PATH}:/var/www/.composer/cache:cached
      - ${SSH_KEY_PATH}/${SSH_KEY_PATH_NAME}:/var/www/.ssh/id_rsa
      - ${SSH_KEY_PATH}/${SSH_KEY_PATH_NAME}.pub:/var/www/.ssh/id_rsa.pub
      - ${SSH_KEY_PATH}/known_hosts:/var/www/.ssh/known_hosts
    environment:
      HISTFILE: /var/www/workspace/.bash_history
      PROMPT_COMMAND: history -a
    env_file: .env

  database:
    image: mariadb:10.5
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ./var/data/mariadb:/var/lib/mysql:cached
    env_file: .env
